version: '3.7'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./project/:/var/www

  nginx:
    image: nginx:1.9
    container_name: nginx
    ports:
    - 80:80
    - 433:433
    volumes:
    - ./project/:/var/www
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/ssl:/etc/nginx/conf.d/ssl
    depends_on:
    - php





